---

- name: Update DLC config from template.
  become: true
  ansible.builtin.template:
    src: dlc_config.json.j2
    dest: /opt/ibm/si/services/dlc/conf/config.json
    owner: root
    group: dlc
    mode: '0640'
  register: dlc_config

- name: Restart DLC service if config file is updated
  become: true
  ansible.builtin.service:
    name: dlc
    state: restarted
  when: dlc_config.changed
  register: restart_dlc_service

- name: Enable DLC service.
  become: true
  ansible.builtin.service:
    name: dlc
    state: started
    enabled: true

- name: Open ports 514 TCP/UDP in local firewall.
  become: true
  ansible.posix.firewalld:
    zone: public
    port: '{{ item }}'
    state: enabled
    permanent: true
    immediate: true
  loop:
    - 514/udp
    - 514/tcp

- name: Configure local firewall to forward port 514 TCP/UDP to 1514 TCP/UDP.
  become: true
  ansible.posix.firewalld:
    rich_rule: '{{ item }}'
    zone: public
    permanent: true
    immediate: true
    state: enabled
  loop:
    - rule family=ipv4 forward-port port=514 protocol=tcp to-port=1514
    - rule family=ipv4 forward-port port=514 protocol=udp to-port=1514

- name: Wait for ports 1514 to become open on the host
  ansible.builtin.wait_for:
    port: 1514
    delay: 30
    sleep: 5
    state: started
    timeout: 300
  when: restart_dlc_service.changed
