---

- name: Install dependencies.
  become: true
  ansible.builtin.yum:
    name: "{{ ibm_dlc_dependencies }}"
    state: present

- name: Create temporary directory for installer.
  ansible.builtin.tempfile:
    state: directory
    prefix: "{{ 1000 | random | hash('md5') }}"
  register: installer_download_dir

- name: Include tasks to download/copy installer files.
  ansible.builtin.include_tasks:
    file: "copy_{{ 'url_' if ibm_dlc_installer is ansible.builtin.url else 'file_' }}installer.yml"

- name: Install IBM DLC through RPM.
  become: true
  ansible.builtin.yum:
    name: '{{ ibmdlcrpmcopy.dest }}'
    state: present
    disable_gpg_check: true # TODO missing IBMs offical signing keys. RPMs for v 1.6.0 and above are signed it would seem
    allow_downgrade: true
  when:  ibm_dlc_installer | basename | split('.') | last | lower == 'rpm'


- name: Block for tgz installation
  block:
    - name: Extract installer tar archive.
      ansible.builtin.unarchive:
        src: '{{ ibmdlcrpmcopy.dest }}'
        dest: '{{ installer_download_dir.path }}'
        remote_src: true
        keep_newer: false

    - name: Delete installer archive.
      ansible.builtin.file:
        path: '{{ ibmdlcrpmcopy.dest }}'
        state: absent

    - name: Run IBM DLC installer script
      become: true
      ansible.builtin.shell: yes | ./install.sh
      args:
        chdir: '{{ installer_download_dir.path }}'
  when: ibm_dlc_installer | basename | split('.') | last | lower == 'tgz'


- name: Cleanup temporary files.
  become: true
  ansible.builtin.file:
    path: '{{ ibmdlcrpmcopy.dest }}'
    state: absent
