---

- name: Assert that role is executed on a supported Operating System
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8'
    msg: "{{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not a supported Operating System for this role."

- name: Include variables specific for the distribution.
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- ansible.builtin.import_tasks:
    file: install.yml
- ansible.builtin.import_tasks:
    file: configure.yml

- name: Find IBM DLC instance file.
  become: True
  ansible.builtin.find:
    paths: /etc/dlc/instance
    file_type: file
    patterns: '[a-z0-9-]+'
    use_regex: True
  register: ibm_dlc_instance_file_search

- name: Print IBM DLC instance ID when ansible_role_ibm_dlc_print_instanceid is set to True
  debug:
    msg: 'IBM DLC instance ID: {{ ibm_dlc_instance_file_search.files[0].path|basename }}'
  when: 
    - ansible_role_ibm_dlc_print_instanceid
    - ibm_dlc_instance_file_search.matched == 1
  