---

- name: Assert that role is executed on a supported Operating System
  assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8'
    msg: "{{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not a supported Operating System for this role."

- name: Include variables specific for the distribution.
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- import_tasks: install.yml
- import_tasks: configure.yml
